/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author DAVID
 */
public class Agregar_Productos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Productos
     */
    public Agregar_Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nomb = new javax.swing.JTextField();
        txt_cant = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbo_CATE = new javax.swing.JComboBox<>();
        btn_actualizar = new javax.swing.JButton();

        setClosable(true);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel1.setText("Nombre");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel2.setText("Cantidad a Agregar");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        txt_nomb.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_nomb.setToolTipText("");
        txt_nomb.setMaximumSize(new java.awt.Dimension(130, 22));
        txt_nomb.setMinimumSize(new java.awt.Dimension(130, 22));
        txt_nomb.setPreferredSize(new java.awt.Dimension(130, 22));
        jPanel2.add(txt_nomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 195, -1));

        txt_cant.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_cant.setMaximumSize(new java.awt.Dimension(130, 22));
        txt_cant.setMinimumSize(new java.awt.Dimension(130, 22));
        txt_cant.setPreferredSize(new java.awt.Dimension(130, 22));
        jPanel2.add(txt_cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 150, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel5.setText("Precio");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 20));

        txt_precio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_precio.setMaximumSize(new java.awt.Dimension(100, 22));
        txt_precio.setMinimumSize(new java.awt.Dimension(100, 22));
        txt_precio.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel2.add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 60, -1));

        btn_agregar.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        btn_agregar.setText("Agregar");
        jPanel2.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel3.setText("Categorias");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 20));

        cbo_CATE.setMaximumSize(new java.awt.Dimension(130, 22));
        cbo_CATE.setMinimumSize(new java.awt.Dimension(130, 22));
        cbo_CATE.setPreferredSize(new java.awt.Dimension(130, 22));
        jPanel2.add(cbo_CATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        btn_actualizar.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        btn_actualizar.setText("Actualizar");
        jPanel2.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_actualizar;
    public javax.swing.JButton btn_agregar;
    public javax.swing.JComboBox<String> cbo_CATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txt_cant;
    public javax.swing.JTextField txt_nomb;
    public javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
