/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Dimension;

/**
 *
 * @author DAVID
 */
public class Principal extends javax.swing.JFrame {

    private static Principal instance;
    
    /**
     * Creates new form Principal
     */
    private Principal() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }
    
    
    public static Principal getInstancia(){
        if (instance == null) {
            instance = new Principal();
        }
        return instance;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        btn_cerrar = new javax.swing.JButton();
        inforPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        lblrol = new javax.swing.JLabel();
        mnbar_barra = new javax.swing.JMenuBar();
        mnu_Us = new javax.swing.JMenu();
        mni_Us = new javax.swing.JMenuItem();
        mni_USINAC = new javax.swing.JMenuItem();
        mnu_Alquiler = new javax.swing.JMenu();
        mni_regCLIENTE = new javax.swing.JMenuItem();
        mnu_Clientes = new javax.swing.JMenu();
        mni_Clientes = new javax.swing.JMenuItem();
        mnu_categorias = new javax.swing.JMenu();
        mni_categoria = new javax.swing.JMenuItem();
        mnu_inventario = new javax.swing.JMenu();
        mni_productos = new javax.swing.JMenuItem();
        mni_gesPro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));

        Escritorio.setMaximumSize(new java.awt.Dimension(1366, 768));
        Escritorio.setMinimumSize(new java.awt.Dimension(1366, 768));
        Escritorio.setName(""); // NOI18N
        Escritorio.setRequestFocusEnabled(false);
        Escritorio.setVerifyInputWhenFocusTarget(false);

        btn_cerrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_cerrar.setText("Cerrar Sesion");
        Escritorio.add(btn_cerrar);
        btn_cerrar.setBounds(1044, 0, 150, 30);

        inforPane.setBackground(new java.awt.Color(251, 233, 225));
        inforPane.setFocusCycleRoot(true);
        inforPane.setMaximumSize(new java.awt.Dimension(1366, 768));
        inforPane.setMinimumSize(new java.awt.Dimension(1366, 768));
        inforPane.setPreferredSize(new java.awt.Dimension(1366, 768));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido Usuario:");

        lblnombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblnombre.setPreferredSize(new java.awt.Dimension(100, 24));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Modo Rol:");

        lblapellido.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblapellido.setPreferredSize(new java.awt.Dimension(100, 24));

        lblrol.setMaximumSize(new java.awt.Dimension(179, 24));
        lblrol.setMinimumSize(new java.awt.Dimension(179, 24));
        lblrol.setPreferredSize(new java.awt.Dimension(179, 24));

        javax.swing.GroupLayout inforPaneLayout = new javax.swing.GroupLayout(inforPane);
        inforPane.setLayout(inforPaneLayout);
        inforPaneLayout.setHorizontalGroup(
            inforPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inforPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inforPaneLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inforPaneLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(954, Short.MAX_VALUE))
        );
        inforPaneLayout.setVerticalGroup(
            inforPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inforPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inforPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Escritorio.add(inforPane);
        inforPane.setBounds(0, 0, 1366, 770);

        getContentPane().add(Escritorio, java.awt.BorderLayout.CENTER);

        mnbar_barra.setBackground(new java.awt.Color(251, 233, 225));
        mnbar_barra.setToolTipText("");

        mnu_Us.setIcon(new javax.swing.ImageIcon("D:\\Github-Trabajos\\Proyecto_Miafe\\Proyecto_Alquiler\\src\\main\\java\\Iconos\\usuario.png")); // NOI18N
        mnu_Us.setText("Usuarios");
        mnu_Us.setMaximumSize(new java.awt.Dimension(100, 30));
        mnu_Us.setMinimumSize(new java.awt.Dimension(100, 30));
        mnu_Us.setPreferredSize(new java.awt.Dimension(100, 25));

        mni_Us.setText("Gestionar Usuarios");
        mnu_Us.add(mni_Us);

        mni_USINAC.setText("Usuarios Inactivos");
        mnu_Us.add(mni_USINAC);

        mnbar_barra.add(mnu_Us);

        mnu_Alquiler.setBackground(new java.awt.Color(251, 233, 225));
        mnu_Alquiler.setIcon(new javax.swing.ImageIcon("D:\\Github-Trabajos\\Proyecto_Miafe\\Proyecto_Alquiler\\src\\main\\java\\Iconos\\Alquiler.png")); // NOI18N
        mnu_Alquiler.setText("Alquiler");
        mnu_Alquiler.setMaximumSize(new java.awt.Dimension(100, 30));
        mnu_Alquiler.setMinimumSize(new java.awt.Dimension(100, 30));
        mnu_Alquiler.setPreferredSize(new java.awt.Dimension(100, 25));

        mni_regCLIENTE.setText("Registro Cliente");
        mni_regCLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_regCLIENTEActionPerformed(evt);
            }
        });
        mnu_Alquiler.add(mni_regCLIENTE);

        mnbar_barra.add(mnu_Alquiler);

        mnu_Clientes.setIcon(new javax.swing.ImageIcon("D:\\Github-Trabajos\\Proyecto_Miafe\\Proyecto_Alquiler\\src\\main\\java\\Iconos\\clientes.png")); // NOI18N
        mnu_Clientes.setText("Clientes");
        mnu_Clientes.setMaximumSize(new java.awt.Dimension(100, 30));
        mnu_Clientes.setMinimumSize(new java.awt.Dimension(100, 30));
        mnu_Clientes.setPreferredSize(new java.awt.Dimension(100, 25));

        mni_Clientes.setText("Gestion de Clientes");
        mni_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_ClientesActionPerformed(evt);
            }
        });
        mnu_Clientes.add(mni_Clientes);

        mnbar_barra.add(mnu_Clientes);

        mnu_categorias.setIcon(new javax.swing.ImageIcon("D:\\Github-Trabajos\\Proyecto_Miafe\\Proyecto_Alquiler\\src\\main\\java\\Iconos\\categoria.png")); // NOI18N
        mnu_categorias.setText("Categoria");
        mnu_categorias.setMaximumSize(new java.awt.Dimension(100, 30));
        mnu_categorias.setMinimumSize(new java.awt.Dimension(100, 30));
        mnu_categorias.setPreferredSize(new java.awt.Dimension(160, 30));

        mni_categoria.setText("Gestion de Categorias");
        mnu_categorias.add(mni_categoria);

        mnbar_barra.add(mnu_categorias);

        mnu_inventario.setIcon(new javax.swing.ImageIcon("D:\\Github-Trabajos\\Proyecto_Miafe\\Proyecto_Alquiler\\src\\main\\java\\Iconos\\inventario.png")); // NOI18N
        mnu_inventario.setText("Inventario");
        mnu_inventario.setMaximumSize(new java.awt.Dimension(100, 30));
        mnu_inventario.setMinimumSize(new java.awt.Dimension(100, 30));
        mnu_inventario.setPreferredSize(new java.awt.Dimension(100, 25));

        mni_productos.setText("Productos");
        mnu_inventario.add(mni_productos);

        mni_gesPro.setText("Gestion de Productos");
        mnu_inventario.add(mni_gesPro);

        mnbar_barra.add(mnu_inventario);

        setJMenuBar(mnbar_barra);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mni_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_ClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mni_ClientesActionPerformed

    private void mni_regCLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_regCLIENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mni_regCLIENTEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane Escritorio;
    public javax.swing.JButton btn_cerrar;
    public javax.swing.JPanel inforPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel lblapellido;
    public javax.swing.JLabel lblnombre;
    public javax.swing.JLabel lblrol;
    public javax.swing.JMenuBar mnbar_barra;
    public javax.swing.JMenuItem mni_Clientes;
    public javax.swing.JMenuItem mni_USINAC;
    public javax.swing.JMenuItem mni_Us;
    public javax.swing.JMenuItem mni_categoria;
    public javax.swing.JMenuItem mni_gesPro;
    public javax.swing.JMenuItem mni_productos;
    public javax.swing.JMenuItem mni_regCLIENTE;
    public javax.swing.JMenu mnu_Alquiler;
    public javax.swing.JMenu mnu_Clientes;
    public javax.swing.JMenu mnu_Us;
    public javax.swing.JMenu mnu_categorias;
    public javax.swing.JMenu mnu_inventario;
    // End of variables declaration//GEN-END:variables
}
