/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Dimension;

/**
 *
 * @author DAVID
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        lblmensaje = new javax.swing.JLabel();
        btn_cerrar = new javax.swing.JButton();
        mnbar_barra = new javax.swing.JMenuBar();
        mnu_Us = new javax.swing.JMenu();
        mni_Us = new javax.swing.JMenuItem();
        mni_USINAC = new javax.swing.JMenuItem();
        mnu_Alquiler = new javax.swing.JMenu();
        mni_regCLIENTE = new javax.swing.JMenuItem();
        mnu_Clientes = new javax.swing.JMenu();
        mni_Clientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_cerrar.setText("Cerrar Sesion");

        Escritorio.setLayer(lblmensaje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(btn_cerrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cerrar)
                .addContainerGap())
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addComponent(btn_cerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        mnu_Us.setText("Usuarios");

        mni_Us.setText("Gestionar Usuarios");
        mnu_Us.add(mni_Us);

        mni_USINAC.setText("Usuarios Inactivos");
        mnu_Us.add(mni_USINAC);

        mnbar_barra.add(mnu_Us);

        mnu_Alquiler.setText("Alquiler");

        mni_regCLIENTE.setText("Registro Cliente");
        mni_regCLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_regCLIENTEActionPerformed(evt);
            }
        });
        mnu_Alquiler.add(mni_regCLIENTE);

        mnbar_barra.add(mnu_Alquiler);

        mnu_Clientes.setText("Clientes");

        mni_Clientes.setText("Gestion de Clientes");
        mni_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_ClientesActionPerformed(evt);
            }
        });
        mnu_Clientes.add(mni_Clientes);

        mnbar_barra.add(mnu_Clientes);

        setJMenuBar(mnbar_barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mni_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_ClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mni_ClientesActionPerformed

    private void mni_regCLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_regCLIENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mni_regCLIENTEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane Escritorio;
    public javax.swing.JButton btn_cerrar;
    public javax.swing.JLabel lblmensaje;
    public javax.swing.JMenuBar mnbar_barra;
    public javax.swing.JMenuItem mni_Clientes;
    public javax.swing.JMenuItem mni_USINAC;
    public javax.swing.JMenuItem mni_Us;
    public javax.swing.JMenuItem mni_regCLIENTE;
    public javax.swing.JMenu mnu_Alquiler;
    public javax.swing.JMenu mnu_Clientes;
    public javax.swing.JMenu mnu_Us;
    // End of variables declaration//GEN-END:variables
}
