/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author yeric
 */
public class RegistroClientes extends javax.swing.JInternalFrame  {

    /**
     * Creates new form RegistroClientes
     */
    public RegistroClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbo_tiDoc = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_priN_cli = new javax.swing.JTextField();
        txt_numD_cli = new javax.swing.JTextField();
        txt_correo_cli = new javax.swing.JTextField();
        txt_apeP_cli = new javax.swing.JTextField();
        txt_telef_cli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_direc_cli = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txt_segN_cli = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_apeM_cli = new javax.swing.JTextField();
        btn_registrarCLI = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        txt_bandera = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("CLIENTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 20, 87, 32);

        jLabel2.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel2.setText("Primer nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(51, 125, 87, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel3.setText("Apellido paterno:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 80, 93, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel4.setText("Tipo de Documento:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 160, 111, 20);

        cbo_tiDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Pasaporte", "Ced_Identidad", "Carnet_Extranjería" }));
        cbo_tiDoc.setMaximumSize(new java.awt.Dimension(130, 22));
        cbo_tiDoc.setMinimumSize(new java.awt.Dimension(130, 22));
        cbo_tiDoc.setPreferredSize(new java.awt.Dimension(130, 22));
        getContentPane().add(cbo_tiDoc);
        cbo_tiDoc.setBounds(190, 160, 130, 22);

        jLabel5.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel5.setText("Número de documento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 200, 130, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel6.setText("Correo electrónico:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 240, 104, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel7.setText("Número telefónico:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 280, 104, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel8.setText("Dirección:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 320, 55, 20);

        txt_priN_cli.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_priN_cli.setMaximumSize(new java.awt.Dimension(130, 22));
        txt_priN_cli.setMinimumSize(new java.awt.Dimension(130, 22));
        txt_priN_cli.setPreferredSize(new java.awt.Dimension(130, 22));
        txt_priN_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_priN_cliActionPerformed(evt);
            }
        });
        getContentPane().add(txt_priN_cli);
        txt_priN_cli.setBounds(190, 80, 137, 22);

        txt_numD_cli.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_numD_cli.setMaximumSize(new java.awt.Dimension(130, 22));
        txt_numD_cli.setMinimumSize(new java.awt.Dimension(130, 22));
        txt_numD_cli.setPreferredSize(new java.awt.Dimension(130, 22));
        txt_numD_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numD_cliActionPerformed(evt);
            }
        });
        getContentPane().add(txt_numD_cli);
        txt_numD_cli.setBounds(190, 200, 130, 22);

        txt_correo_cli.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_correo_cli.setMaximumSize(new java.awt.Dimension(130, 22));
        txt_correo_cli.setMinimumSize(new java.awt.Dimension(130, 22));
        txt_correo_cli.setPreferredSize(new java.awt.Dimension(130, 22));
        getContentPane().add(txt_correo_cli);
        txt_correo_cli.setBounds(190, 240, 130, 22);

        txt_apeP_cli.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_apeP_cli.setMaximumSize(new java.awt.Dimension(130, 22));
        txt_apeP_cli.setMinimumSize(new java.awt.Dimension(130, 22));
        txt_apeP_cli.setPreferredSize(new java.awt.Dimension(130, 22));
        getContentPane().add(txt_apeP_cli);
        txt_apeP_cli.setBounds(510, 80, 138, 22);

        txt_telef_cli.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_telef_cli.setMaximumSize(new java.awt.Dimension(130, 22));
        txt_telef_cli.setMinimumSize(new java.awt.Dimension(130, 22));
        txt_telef_cli.setPreferredSize(new java.awt.Dimension(130, 22));
        getContentPane().add(txt_telef_cli);
        txt_telef_cli.setBounds(190, 280, 137, 22);

        txt_direc_cli.setColumns(20);
        txt_direc_cli.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_direc_cli.setRows(5);
        jScrollPane1.setViewportView(txt_direc_cli);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 320, 294, 126);

        jLabel9.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel9.setText("Segundo nombre:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 80, 100, 20);

        txt_segN_cli.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_segN_cli.setMaximumSize(new java.awt.Dimension(130, 22));
        txt_segN_cli.setMinimumSize(new java.awt.Dimension(130, 22));
        txt_segN_cli.setPreferredSize(new java.awt.Dimension(130, 22));
        getContentPane().add(txt_segN_cli);
        txt_segN_cli.setBounds(190, 120, 137, 22);

        jLabel10.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel10.setText("Apellido materno:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(390, 120, 97, 20);

        txt_apeM_cli.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_apeM_cli.setMaximumSize(new java.awt.Dimension(130, 22));
        txt_apeM_cli.setMinimumSize(new java.awt.Dimension(130, 22));
        txt_apeM_cli.setPreferredSize(new java.awt.Dimension(130, 22));
        getContentPane().add(txt_apeM_cli);
        txt_apeM_cli.setBounds(510, 120, 138, 22);

        btn_registrarCLI.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        btn_registrarCLI.setText("CONTINUAR");
        getContentPane().add(btn_registrarCLI);
        btn_registrarCLI.setBounds(290, 480, 130, 26);

        btn_limpiar.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        btn_limpiar.setText("LIMPIAR");
        getContentPane().add(btn_limpiar);
        btn_limpiar.setBounds(50, 370, 90, 26);

        txt_bandera.setEditable(false);
        txt_bandera.setText("0");
        getContentPane().add(txt_bandera);
        txt_bandera.setBounds(595, 241, 64, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_priN_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_priN_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_priN_cliActionPerformed

    private void txt_numD_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numD_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numD_cliActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_limpiar;
    public javax.swing.JButton btn_registrarCLI;
    public javax.swing.JComboBox<String> cbo_tiDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField txt_apeM_cli;
    public javax.swing.JTextField txt_apeP_cli;
    public javax.swing.JTextField txt_bandera;
    public javax.swing.JTextField txt_correo_cli;
    public javax.swing.JTextArea txt_direc_cli;
    public javax.swing.JTextField txt_numD_cli;
    public javax.swing.JTextField txt_priN_cli;
    public javax.swing.JTextField txt_segN_cli;
    public javax.swing.JTextField txt_telef_cli;
    // End of variables declaration//GEN-END:variables
}
